/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/RoomScene.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RoomScene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="WallsF" geometry={nodes.WallsF.geometry} material={materials.BakeMaterial} position={[-3.578, 1.77, -1.723]} />
      <mesh name="Calendar" geometry={nodes.Calendar.geometry} material={materials.BakeMaterial} position={[-5.947, 2.128, -1.636]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Desk2" geometry={nodes.Desk2.geometry} material={materials.BakeMaterial} position={[-5.278, 0.814, -2.532]} />
      <mesh name="Mat" geometry={nodes.Mat.geometry} material={materials.BakeMaterial} position={[-3.214, 0.057, -1.175]} />
      <mesh name="ShelfUpper" geometry={nodes.ShelfUpper.geometry} material={materials.BakeMaterial} position={[-2.938, 1.651, -3.065]} rotation={[0, -1.571, 0]} />
      <mesh name="Phone" geometry={nodes.Phone.geometry} material={materials.BakeMaterial} position={[-4.736, 0.888, -3.185]} rotation={[0, -0.903, -1.295]} />
      <mesh name="CupBoard" geometry={nodes.CupBoard.geometry} material={materials.BakeMaterial} position={[-5.308, 0.341, 0.02]} />
      <mesh name="Slippies" geometry={nodes.Slippies.geometry} material={materials.BakeMaterial} position={[-4.484, 0.068, -2.251]} />
      <mesh name="Darwaaza" geometry={nodes.Darwaaza.geometry} material={materials.BakeMaterial} position={[1.124, 1.306, -1.774]} rotation={[0, -1.571, 0]} />
      <mesh name="Clock" geometry={nodes.Clock.geometry} material={materials.BakeMaterial} position={[-5.456, 0.916, -1.366]} rotation={[0, -0.279, 0]} />
      <mesh name="Frame004" geometry={nodes.Frame004.geometry} material={materials.BakeMaterial} position={[-2.043, 1.658, -3.342]} rotation={[1.314, 0, 0]} />
      <mesh name="Frame005" geometry={nodes.Frame005.geometry} material={materials.BakeMaterial} position={[-2.514, 1.176, -3.297]} rotation={[1.314, 0, 0]} />
      <mesh name="Bed" geometry={nodes.Bed.geometry} material={materials.BakeMaterial} position={[0.127, 0.437, 1.615]} rotation={[0, 1.571, 0]} />
      <mesh name="WallsB" geometry={nodes.WallsB.geometry} material={materials.BakeMaterial} position={[-3.397, 1.59, -1.468]} />
      <mesh name="Sil" geometry={nodes.Sil.geometry} material={materials.BakeMaterial} position={[-2.288, 1.493, 2.243]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh name="Ceiling_Main" geometry={nodes.Ceiling_Main.geometry} material={materials.BakeMaterial} position={[-4.197, 3.155, -0.736]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="Lapp" geometry={nodes.Lapp.geometry} material={materials.BakeMaterial} position={[-4.304, 0.968, -3.44]} rotation={[0, -1.571, 0]} />
      <mesh name="SideDesk" geometry={nodes.SideDesk.geometry} material={materials.BakeMaterial} position={[-5.045, 0.44, -1.378]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="Bookshelf2" geometry={nodes.Bookshelf2.geometry} material={materials.BakeMaterial} position={[-1.074, 1.712, -3.375]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="Floor" geometry={nodes.Floor.geometry} material={materials.BakeMaterial} position={[-5.258, 0.033, -2.982]} />
      <mesh name="LappyStand" geometry={nodes.LappyStand.geometry} material={materials.BakeMaterial} position={[-4.173, 0.829, -3.342]} />
      <mesh name="Piggy" geometry={nodes.Piggy.geometry} material={materials.BakeMaterial} position={[-5.567, 0.579, 0.03]} rotation={[Math.PI / 2, 0, -2.224]} />
      <mesh name="Succulent_plant" geometry={nodes.Succulent_plant.geometry} material={materials.BakeMaterial} position={[-3.855, 0.813, -3.434]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="tablet" geometry={nodes.tablet.geometry} material={materials.BakeMaterial} position={[-5.343, 1.045, -2.199]} rotation={[-Math.PI / 2, 0.751, Math.PI / 2]} />
      <mesh name="Trophy" geometry={nodes.Trophy.geometry} material={materials.BakeMaterial} position={[-2.49, 1.856, -3.424]} rotation={[0, 1.285, 0]} />
      <mesh name="KeyBoard" geometry={nodes.KeyBoard.geometry} material={materials.BakeMaterial} position={[-4.026, 0.85, -3.148]} rotation={[0.046, 0, 0]} />
      <mesh name="Vase" geometry={nodes.Vase.geometry} material={materials.BakeMaterial} position={[-5.545, 0.941, -3.362]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="Stylus" geometry={nodes.Stylus.geometry} material={materials.BakeMaterial} position={[-5.174, 0.987, -2.938]} rotation={[0, 0.959, Math.PI]} />
      <mesh name="soccer_ball" geometry={nodes.soccer_ball.geometry} material={materials.BakeMaterial} position={[-1.461, 0.248, -3.465]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="Merch2" geometry={nodes.Merch2.geometry} material={materials.BakeMaterial} position={[-5.553, 1.811, -0.103]} rotation={[Math.PI / 2, 0, -0.464]} />
      <mesh name="Merch" geometry={nodes.Merch.geometry} material={materials.BakeMaterial} position={[-5.553, 1.811, 0.212]} rotation={[Math.PI / 2, 0, -0.399]} />
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.BakeMaterial} position={[-3.703, 1.607, -3.734]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="IDHook" geometry={nodes.IDHook.geometry} material={materials.BakeMaterial} position={[-3.696, 2.017, -3.74]} />
      <mesh name="KeyBoardKeys" geometry={nodes.KeyBoardKeys.geometry} material={materials.BakeMaterial} position={[-4.026, 0.85, -3.148]} rotation={[0.046, 0, 0]} />
      <mesh name="BOUKS" geometry={nodes.BOUKS.geometry} material={materials.BakeMaterial} position={[-3.38, 1.59, -1.468]} />
      <mesh name="TabScreen" geometry={nodes.TabScreen.geometry} material={materials.TabScreen} position={[-5.328, 1.061, -2.199]} rotation={[-Math.PI / 2, 0.751, Math.PI / 2]} />
      <mesh name="LappyScreen" geometry={nodes.LappyScreen.geometry} material={materials.LappyScreen} position={[-4.31, 1.194, -3.564]} rotation={[0, -1.571, 0]} />
      <mesh name="PhoneScreen" geometry={nodes.PhoneScreen.geometry} material={materials.PhoneScreen} position={[-4.755, 1.008, -3.208]} rotation={[0, -0.903, -1.295]} />
      <mesh name="ClockScreen" geometry={nodes.ClockScreen.geometry} material={materials['AlarmScreen.001']} position={[-5.402, 0.916, -1.313]} rotation={[0, -0.279, 0]} />
    </group>
  )
}

useGLTF.preload('/RoomScene.gltf')
