/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 test.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF,useTexture } from '@react-three/drei'
//import BakedFile from '../assets/baked_room.png';
import * as THREE from 'three';

export function Model_Test(props) {
  const texture=useTexture('baked_room.png');
  texture.flipY=false;
  texture.colorSpace=THREE.SRGBColorSpace;
  const textureMaterial=new THREE.MeshStandardMaterial({
    map:texture,
  })
  const { nodes, materials } = useGLTF('models/Test.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BOUKS.geometry} material={textureMaterial} position={[-3.38, 1.59, -1.468]} />
      <mesh geometry={nodes.WallsF.geometry} material={textureMaterial} position={[-3.578, 1.77, -1.723]}>
        <mesh geometry={nodes.IDHook.geometry} material={textureMaterial} position={[-0.117, 0.248, -2.017]}>
          <mesh geometry={nodes.Plane.geometry} material={textureMaterial} position={[-0.007, -0.411, 0.006]} rotation={[Math.PI / 2, 0, 0]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.AlarmClock001.geometry} material={textureMaterial} position={[-5.947, 2.128, -1.636]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Desk2.geometry} material={textureMaterial} position={[-5.278, 0.814, -2.532]}>
        <mesh geometry={nodes.Clock.geometry} material={textureMaterial} position={[-0.178, 0.102, 1.166]} rotation={[0, -0.279, 0]} />
        <mesh geometry={nodes.tablet.geometry} material={textureMaterial} position={[-0.065, 0.231, 0.333]} rotation={[-Math.PI / 2, 0.751, Math.PI / 2]} />
        <mesh geometry={nodes.Vase.geometry} material={textureMaterial} position={[-0.267, 0.127, -0.83]} rotation={[Math.PI, 0, Math.PI]} />
      </mesh>
      <mesh geometry={nodes.Mat.geometry} material={textureMaterial} position={[-3.214, 0.057, -1.175]} />
      <mesh geometry={nodes.ShelfUpper.geometry} material={textureMaterial} position={[-2.938, 1.651, -3.065]} rotation={[0, -1.571, 0]}>
        <group position={[-0.277, 0.007, -0.894]} rotation={[Math.PI / 2, 0.257, -Math.PI / 2]}>
          <mesh geometry={nodes.Cube067.geometry} material={textureMaterial} />
          <mesh geometry={nodes.Cube067_1.geometry} material={nodes.Cube067_1.material} />
        </group>
      </mesh>
      <mesh geometry={nodes.Phone.geometry} material={textureMaterial} position={[-4.736, 0.888, -3.185]} rotation={[0, -0.903, -1.295]} />
      <mesh geometry={nodes.Cube011.geometry} material={textureMaterial} position={[-5.308, 0.341, 0.02]} />
      <mesh geometry={nodes.Slippies.geometry} material={textureMaterial} position={[-4.484, 0.068, -2.251]} />
      <group position={[1.124, 1.306, -1.774]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Cube058.geometry} material={textureMaterial} />
        <mesh geometry={nodes.Cube058_1.geometry} material={nodes.Cube058_1.material} />
      </group>
      <mesh geometry={nodes.Frame005.geometry} material={textureMaterial} position={[-2.514, 1.176, -3.297]} rotation={[1.314, 0, 0]} />
      <mesh geometry={nodes.Bed.geometry} material={textureMaterial} position={[0.127, 0.437, 1.615]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.WallsB.geometry} material={textureMaterial} position={[-3.397, 1.59, -1.468]} />
      <group position={[-2.288, 1.493, 2.243]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube078.geometry} material={textureMaterial} />
        <mesh geometry={nodes.Cube078_1.geometry} material={textureMaterial} />
      </group>
      <mesh geometry={nodes.Ceiling_Main.geometry} material={textureMaterial} position={[-4.197, 3.155, -0.736]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.SideDesk.geometry} material={textureMaterial} position={[-5.045, 0.44, -1.378]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Bookshelf2.geometry} material={textureMaterial} position={[-1.074, 1.712, -3.375]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.soccer_ball.geometry} material={textureMaterial} position={[0.091, -1.464, -0.387]} rotation={[0, 1.571, 0]} />
      </mesh>
      <mesh geometry={nodes.Floor.geometry} material={textureMaterial} position={[-5.258, 0.033, -2.982]} />
      <mesh geometry={nodes.LappyStand.geometry} material={textureMaterial} position={[-4.173, 0.829, -3.342]}>
        <mesh geometry={nodes.Lapp.geometry} material={textureMaterial} position={[-0.13, 0.139, -0.098]} rotation={[0, -1.571, 0]} />
      </mesh>
      <mesh geometry={nodes.Piggy.geometry} material={textureMaterial} position={[-5.567, 0.579, 0.03]} rotation={[Math.PI / 2, 0, -2.224]} />
      <mesh geometry={nodes.Succulent_plant.geometry} material={textureMaterial} position={[-3.855, 0.813, -3.434]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Trophy001.geometry} material={textureMaterial} position={[-2.49, 1.856, -3.424]} rotation={[0, 1.285, 0]} />
      <mesh geometry={nodes.KeyBoard.geometry} material={textureMaterial} position={[-4.026, 0.85, -3.148]} rotation={[0.046, 0, 0]} />
      <mesh geometry={nodes.DOL.geometry} material={textureMaterial} position={[-5.174, 0.987, -2.938]} rotation={[0, 0.959, Math.PI]} />
      <mesh geometry={nodes.DOL001.geometry} material={textureMaterial} position={[-5.174, 0.987, -2.938]} rotation={[0, 0.959, Math.PI]} />
      <mesh geometry={nodes.Merch003.geometry} material={textureMaterial} position={[-5.553, 1.811, -0.103]} rotation={[Math.PI / 2, 0, -0.464]} />
      <mesh geometry={nodes.Merch.geometry} material={textureMaterial} position={[-5.553, 1.811, 0.212]} rotation={[Math.PI / 2, 0, -0.399]} />
      <mesh geometry={nodes.KeyBoardKeys.geometry} material={textureMaterial} position={[-4.026, 0.85, -3.148]} rotation={[0.046, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Test.gltf')
